apiVersion: v1
kind: ConfigMap
metadata:
  name: aks-workshop-gateway-env
data:
  config.service.endpoint: "https://apim-workshop-hybrid.management.azure-api.net/subscriptions/6bdcc705-8db6-4029-953a-e749070e6db6/resourceGroups/apim-workshop-rg/providers/Microsoft.ApiManagement/service/apim-workshop-hybrid?api-version=2021-01-01-preview"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-workshop-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-workshop-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: aks-workshop-gateway
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: aks-workshop-gateway
        image: mcr.microsoft.com/azure-api-management/gateway:latest
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /internal-status-0123456789abcdef
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 1
            memory: 1Gi
        env:
        - name: config.service.auth
          valueFrom:
            secretKeyRef:
              name: aks-workshop-gateway-token
              key: value
        envFrom:
        - configMapRef:
            name: aks-workshop-gateway-env
      nodeSelector:
        agentpool: akssyspool
---
apiVersion: v1
kind: Service
metadata:
  name: aks-workshop-gateway
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8081
  selector:
    app: aks-workshop-gateway