ingress:
  name: smoke-ingress
  namespace: smoke
  annotations:
   ingressClass: nginx
   enableCors: "true"
   rewriteTarget: /$1
  tls:
  - hosts:
    - "*.internal.wkshpdev.com"
    secretName: aks-workshop-tls-secret
  hosts:
  - name: smoke-prv.internal.wkshpdev.com
    paths:
    - path: /nginx/?(.*)
      pathType: prefix
      service: nginx-svc
      port: 80
  