controller:
  replicaCount: 2
  # podAnnotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/port: "10254"
  extraArgs:
    enable-ssl-passthrough: "true"
  metrics:
    enabled: "true"
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"      





