apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.developer.roleName }}
  namespace: {{ .Values.developer.roleNamespace }}
rules:
{{- range $rule := .Values.developer.rules}}
- apiGroups: {{ $rule.apiGroups }}
  resources: {{ $rule.resources }}
  verbs: {{ $rule.verbs }}
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.developer.bindingName }}
  namespace: {{ .Values.developer.bindingNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.developer.roleName }}
subjects:
{{- range $subject := .Values.developer.subjects}}
- apiGroup: rbac.authorization.k8s.io
  name: {{  $subject.name }}
  kind: {{  $subject.kind }}
{{- end }}